[versions]

minecraft = "26.2"
loader = "0.19.3"
loom = "1.17-SNAPSHOT"
fabric = "0.153.0+26.2"

gson = "2.13.2"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
loader = { module = "net.fabricmc:fabric-loader", version.ref = "loader" }
api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

[plugins]
loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }